INSERT INTO test_ukeess.departments (deptName) VALUES ('ACCOUNTING');
INSERT INTO test_ukeess.departments (deptName) VALUES ('RESEARCH');
INSERT INTO test_ukeess.departments (deptName) VALUES ('SALES');
INSERT INTO test_ukeess.departments (deptName) VALUES ('OPERATIONS');
INSERT INTO test_ukeess.departments (deptName) VALUES ('ACTIVE_BOYS');

INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Vlad', 0, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Petro', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('James', 0, 2);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Ford', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Scott', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Adams', 0, 3);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Jackie', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Olga', 0, 2);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Inna', 1, 4);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Valeria', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Ward', 1, 2);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Jones', 0, 3);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Clark', 0, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Blake', 0, 4);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Tonya', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Dima', 1, 1);

INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);
INSERT INTO test_ukeess.employees(empName, empActive, emp_dpID) VALUES ('Sofia', 1, 1);

INSERT INTO test_ukeess.users(username, password) VALUES ('user','$2a$10$qxXuwZeeHO9/Bc48tSXQoe4epv5Y3PRgfTS0qCgveyyOuLlrKhuiW');